# Generated by Django 5.1.15 on 2026-06-23 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=160)),
                ('icon', models.CharField(max_length=30)),
                ('got', models.BooleanField(default=False)),
                ('date_label', models.CharField(blank=True, max_length=20)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('is_elo', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('tag', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('season', models.CharField(max_length=80)),
                ('days_left', models.IntegerField(default=0)),
                ('played', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('initials', models.CharField(max_length=4)),
                ('color', models.CharField(default='#3f6f8f', max_length=9)),
                ('elo', models.IntegerField(default=1500)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('is_me', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-elo'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('live', 'live'), ('open', 'open'), ('done', 'done')], default='open', max_length=8)),
                ('players', models.IntegerField(default=0)),
                ('cap', models.IntegerField(blank=True, null=True)),
                ('prize', models.CharField(blank=True, max_length=20)),
                ('fee', models.CharField(blank=True, max_length=20)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('1vs1', '1vs1'), ('2vs2', '2vs2')], default='1vs1', max_length=8)),
                ('played_at', models.DateTimeField()),
                ('score_a', models.IntegerField()),
                ('score_b', models.IntegerField()),
                ('elo_change', models.IntegerField(default=0)),
                ('team_a', models.ManyToManyField(related_name='matches_as_a', to='api.player')),
                ('team_b', models.ManyToManyField(related_name='matches_as_b', to='api.player')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='LeagueStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='api.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EloHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField()),
                ('elo_after', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='api.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='api.player')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_event', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=30)),
                ('text', models.TextField()),
                ('time_label', models.CharField(blank=True, max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.player')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BracketMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('quarti', 'quarti'), ('semi', 'semi'), ('finale', 'finale')], max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('score_a', models.IntegerField(blank=True, null=True)),
                ('score_b', models.IntegerField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('live', models.BooleanField(default=False)),
                ('player_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.player')),
                ('player_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket', to='api.tournament')),
            ],
            options={
                'ordering': ['round', 'order'],
            },
        ),
    ]
