# Generated by Django 5.1.15 on 2026-07-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_player_is_me_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('backoffice', 'Back office'), ('admin', 'Admin')], default='player', max_length=16),
        ),
    ]
